In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("master_credit_data_clean.csv")

df.shape

(24255, 10)

In [2]:
df.head()

   100000  3  0  11  24  35  14288   6  15  33
0  100001  4  0  19  19  21  13057  13  22  25
1  100002  4  3   2  17  32  17242   1  15  26
2  100003  3  0   9  15  32  10156  10  10  10
3  100004  3  1  11  18  29  15061  14  14  14
4  100005  3  3   0  17  17  17666   3  17  17

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24255 entries, 0 to 24254
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   100000  24255 non-null  int64
 1   3       24255 non-null  int64
 2   0       24255 non-null  int64
 3   11      24255 non-null  object
 4   24      24255 non-null  int64
 5   35      24255 non-null  int64
 6   14288   24255 non-null  int64
 7   6       24255 non-null  object
 8   15      24255 non-null  int64
 9   33      24255 non-null  int64
dtypes: int64(8), object(2)
memory usage: 1.9+ MB

In [4]:
df.describe()

,100000,3,0,24,35,14288,15,33
count,24255.000000,24255.000000,24255.000000,24255.000000,24255.000000,24255.000000,24255.000000,24255.000000
mean,112494.804370,1.982684,1.193898,18.127231,26.379468,10469.336590,14.368048,21.613605
std,7219.863523,1.413553,1.163884,6.277939,7.180222,5496.001164,5.534160,6.964164
min,100001.000000,0.000000,0.000000,5.000000,10.000000,1000.000000,3.000000,5.000000
25%,106238.500000,1.000000,0.000000,13.000000,21.000000,5707.000000,10.000000,16.000000
50%,112496.000000,2.000000,1.000000,18.000000,26.000000,10429.000000,14.000000,22.000000
75%,118742.500000,3.000000,2.000000,23.000000,32.000000,15249.500000,19.000000,27.000000
max,124999.000000,4.000000,4.000000,29.000000,39.000000,19999.000000,24.000000,34.000000

In [5]:
df = pd.read_csv("master_credit_data_clean.csv", header=None)

df.shape

(24256, 10)

In [6]:
df.columns = [
    "Client_ID",
    "Applied",
    "Approved",
    "Total_Tradelines_6m_In",
    "Total_Tradelines_1y_In",
    "Total_Tradelines_2y_In",
    "Max_Trade_3m_Out",
    "Total_Enquiry_6m_In",
    "Total_Enquiry_1y_In",
    "Total_Enquiry_2y_In"
]

In [7]:
df.head()

,Client_ID,Applied,Approved,Total_Tradelines_6m_In,Total_Tradelines_1y_In,Total_Tradelines_2y_In,Max_Trade_3m_Out,Total_Enquiry_6m_In,Total_Enquiry_1y_In,Total_Enquiry_2y_In
0,100000,3,0,11,24,35,14288,6,15,33
1,100001,4,0,19,19,21,13057,13,22,25
2,100002,4,3,2,17,32,17242,1,15,26
3,100003,3,0,9,15,32,10156,10,10,10
4,100004,3,1,11,18,29,15061,14,14,14

In [8]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24256 entries, 0 to 24255
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Client_ID               24256 non-null  int64
 1   Applied                 24256 non-null  int64
 2   Approved                24256 non-null  int64
 3   Total_Tradelines_6m_In  24256 non-null  object
 4   Total_Tradelines_1y_In  24256 non-null  int64
 5   Total_Tradelines_2y_In  24256 non-null  int64
 6   Max_Trade_3m_Out        24256 non-null  int64
 7   Total_Enquiry_6m_In     24256 non-null  object
 8   Total_Enquiry_1y_In     24256 non-null  int64
 9   Total_Enquiry_2y_In     24256 non-null  int64
dtypes: int64(8), object(2)
memory usage: 1.9+ MB

In [9]:
df = pd.read_csv(
    "master_credit_data_clean.csv",
    header=None,
    na_values="\\N"
)

In [10]:
df.columns = [
    "Client_ID",
    "Applied",
    "Approved",
    "Total_Tradelines_6m_In",
    "Total_Tradelines_1y_In",
    "Total_Tradelines_2y_In",
    "Max_Trade_3m_Out",
    "Total_Enquiry_6m_In",
    "Total_Enquiry_1y_In",
    "Total_Enquiry_2y_In"
]

In [11]:
df.isnull().sum()

Client_ID                   0
Applied                     0
Approved                    0
Total_Tradelines_6m_In    197
Total_Tradelines_1y_In      0
Total_Tradelines_2y_In      0
Max_Trade_3m_Out            0
Total_Enquiry_6m_In       365
Total_Enquiry_1y_In         0
Total_Enquiry_2y_In         0
dtype: int64

In [12]:
df["Total_Tradelines_6m_In"].median()

10.0

In [13]:

df["Total_Enquiry_6m_In"].median()

7.0

In [14]:
df["Total_Tradelines_6m_In"].fillna(10, inplace=True)
df["Total_Enquiry_6m_In"].fillna(7, inplace=True)

df.isnull().sum()

C:\Users\gsree\AppData\Local\Temp\ipykernel_19464\4029938016.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Total_Tradelines_6m_In"].fillna(10, inplace=True)
C:\Users\gsree\AppData\Local\Temp\ipykernel_19464\4029938016.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Total_Enquiry_6m_In"].fillna(7, inplace=True)

Client_ID                 0
Applied                   0
Approved                  0
Total_Tradelines_6m_In    0
Total_Tradelines_1y_In    0
Total_Tradelines_2y_In    0
Max_Trade_3m_Out          0
Total_Enquiry_6m_In       0
Total_Enquiry_1y_In       0
Total_Enquiry_2y_In       0
dtype: int64

In [15]:
df["Total_Tradelines_6m_In"] = df["Total_Tradelines_6m_In"].fillna(10)
df["Total_Enquiry_6m_In"] = df["Total_Enquiry_6m_In"].fillna(7)

In [16]:
df["Target"] = (df["Approved"] > 0).astype(int)

df["Target"].value_counts()

Target
1    15501
0     8755
Name: count, dtype: int64

# Feature Engg

In [17]:
df["Approval_Rate"] = df["Approved"] / df["Applied"].replace(0, 1)

In [18]:
df["Approval_Rate"] = np.where(
    df["Applied"] > 0,
    df["Approved"] / df["Applied"],
    0
)

In [19]:
df["Enquiry_Intensity"] = np.where(
    df["Total_Enquiry_1y_In"] > 0,
    df["Total_Enquiry_6m_In"] / df["Total_Enquiry_1y_In"],
    0
)

In [20]:
df["Tradeline_Growth"] = df["Total_Tradelines_6m_In"] - (
    df["Total_Tradelines_2y_In"] / 4
)

In [21]:
df["Debt_Pressure"] = df["Max_Trade_3m_Out"] / (df["Total_Tradelines_6m_In"] + 1)

In [22]:
df[[
    "Approval_Rate",
    "Enquiry_Intensity",
    "Tradeline_Growth",
    "Debt_Pressure"
]].describe()

       Approval_Rate  Enquiry_Intensity  Tradeline_Growth  Debt_Pressure
count   24256.000000       24256.000000      24256.000000   24256.000000
mean        0.520088           0.543597          2.916753    1882.715114
std         0.444228           0.343746          5.951870    2799.229896
min         0.000000           0.000000         -9.750000      50.000000
25%         0.000000           0.250000         -2.000000     544.650000
50%         0.500000           0.521739          3.000000     991.934874
75%         1.000000           0.916667          8.000000    1870.531250
max         1.000000           2.333333         14.250000   19995.000000

In [23]:
(df["Total_Enquiry_6m_In"] > df["Total_Enquiry_1y_In"]).sum()

np.int64(32)

In [24]:
df["Total_Enquiry_1y_In"] = np.maximum(
    df["Total_Enquiry_1y_In"],
    df["Total_Enquiry_6m_In"]
)

In [25]:
(df["Total_Enquiry_6m_In"] > df["Total_Enquiry_1y_In"]).sum()

np.int64(0)

In [26]:
df["Enquiry_Intensity"] = np.where(
    df["Total_Enquiry_1y_In"] > 0,
    df["Total_Enquiry_6m_In"] / df["Total_Enquiry_1y_In"],
    0
)

df["Enquiry_Intensity"].describe()

count    24256.000000
mean         0.543055
std          0.342513
min          0.000000
25%          0.250000
50%          0.521739
75%          0.916667
max          1.000000
Name: Enquiry_Intensity, dtype: float64

# Modeling

In [27]:
X = df.drop(columns=["Client_ID", "Approved", "Target"])
y = df["Target"]

X.shape

(24256, 12)

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

y_train.value_counts()
y_test.value_counts()

Target
1    3101
0    1751
Name: count, dtype: int64

In [29]:
print("Train Distribution")
print(y_train.value_counts())

print("\nTest Distribution")
print(y_test.value_counts())

Train Distribution
Target
1    12400
0     7004
Name: count, dtype: int64

Test Distribution
Target
1    3101
0    1751
Name: count, dtype: int64

# Scaling

In [30]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Logistic Regression

In [31]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

# Evaluate

In [32]:
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report

y_pred = log_model.predict(X_test_scaled)
y_prob = log_model.predict_proba(X_test_scaled)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC AUC:", roc_auc_score(y_test, y_prob))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

Accuracy: 1.0
ROC AUC: 1.0

Confusion Matrix
[[1751    0]
 [   0 3101]]

Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1751
           1       1.00      1.00      1.00      3101

    accuracy                           1.00      4852
   macro avg       1.00      1.00      1.00      4852
weighted avg       1.00      1.00      1.00      4852

In [33]:
X = df.drop(columns=[
    "Client_ID",
    "Approved",
    "Target",
    "Approval_Rate"   # remove leakage
])

In [34]:
X.columns

Index(['Applied', 'Total_Tradelines_6m_In', 'Total_Tradelines_1y_In',
       'Total_Tradelines_2y_In', 'Max_Trade_3m_Out', 'Total_Enquiry_6m_In',
       'Total_Enquiry_1y_In', 'Total_Enquiry_2y_In', 'Enquiry_Intensity',
       'Tradeline_Growth', 'Debt_Pressure'],
      dtype='object')

# Retrain Model

In [35]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report, accuracy_score

# Split again
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

# Scale
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train
log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train_scaled, y_train)

# Evaluate
y_pred = log_model.predict(X_test_scaled)
y_prob = log_model.predict_proba(X_test_scaled)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC AUC:", roc_auc_score(y_test, y_prob))
print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.7260923330585326
ROC AUC: 0.7760934876481878

Confusion Matrix
[[1151  600]
 [ 729 2372]]

# Train Random Forest

In [36]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

print("RF Accuracy:", accuracy_score(y_test, y_pred_rf))
print("RF ROC AUC:", roc_auc_score(y_test, y_prob_rf))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred_rf))

RF Accuracy: 0.8413025556471558
RF ROC AUC: 0.7848861782763469

Confusion Matrix
[[ 992  759]
 [  11 3090]]

# Feature Detection

In [37]:
import pandas as pd

feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
}).sort_values(by="Importance", ascending=False)

feature_importance

                   Feature  Importance
0                  Applied    0.467119
10           Debt_Pressure    0.081395
4         Max_Trade_3m_Out    0.081096
9         Tradeline_Growth    0.058432
7      Total_Enquiry_2y_In    0.054021
3   Total_Tradelines_2y_In    0.049400
8        Enquiry_Intensity    0.047937
2   Total_Tradelines_1y_In    0.046252
6      Total_Enquiry_1y_In    0.044400
5      Total_Enquiry_6m_In    0.036172
1   Total_Tradelines_6m_In    0.033775

In [38]:
X_no_applied = X.drop(columns=["Applied"])

X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X_no_applied, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

rf_model2 = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_model2.fit(X_train2, y_train2)

y_prob2 = rf_model2.predict_proba(X_test2)[:, 1]

print("RF ROC AUC (No Applied):", roc_auc_score(y_test2, y_prob2))

RF ROC AUC (No Applied): 0.5049519775036184

# Risk Score

In [39]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

risk_features = [
    "Enquiry_Intensity",
    "Debt_Pressure",
    "Tradeline_Growth"
]

df_scaled = scaler.fit_transform(df[risk_features])

df["Behavioral_Risk_Score"] = df_scaled.mean(axis=1)

df["Behavioral_Risk_Score"].describe()

count    24256.000000
mean         0.387575
std          0.132948
min          0.034487
25%          0.286022
50%          0.386872
75%          0.489561
max          0.764019
Name: Behavioral_Risk_Score, dtype: float64

# Risk Segment

In [40]:
df["Risk_Segment"] = pd.qcut(
    df["Behavioral_Risk_Score"],
    q=3,
    labels=["Low", "Medium", "High"]
)

df["Risk_Segment"].value_counts()

Risk_Segment
Low       8086
Medium    8085
High      8085
Name: count, dtype: int64

# Segment Validation

In [41]:
df.groupby("Risk_Segment")[[
    "Enquiry_Intensity",
    "Debt_Pressure",
    "Tradeline_Growth"
]].mean()

C:\Users\gsree\AppData\Local\Temp\ipykernel_19464\899291198.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("Risk_Segment")[[

              Enquiry_Intensity  Debt_Pressure  Tradeline_Growth
Risk_Segment
Low                    0.206518    1930.285250          0.170140
Medium                 0.527773    1830.093409          3.317471
High                   0.894915    1887.760800          5.262987

# Save the Dataset

In [42]:
df.to_csv("credit_risk_behavioral_final.csv", index=False)

# Save the Model

In [43]:
import joblib
joblib.dump(rf_model, "rf_behavioral_model.pkl")

['rf_behavioral_model.pkl']

In [44]:
df.to_csv("credit_risk_behavioral_final.csv", index=False)